package com.gmail.dmytro.ui.view.admin.carrier;

import com.gmail.dmytro.backend.data.entity.Carrier;
import com.gmail.dmytro.backend.data.entity.Product;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.*;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class CarrierAdminViewDesign extends VerticalLayout {
	protected TextField search;
	protected Button add;
	protected CssLayout listParent;
	protected Grid<Carrier> list;
	protected VerticalLayout form;
	protected TextField code;
	protected TextField name;
	protected TextField type;
	protected TextField massCap;
	protected TextField volumeCap;
	protected TextField speed;
	protected Button update;
	protected Button cancel;
	protected Button delete;

	public CarrierAdminViewDesign() {
		Design.read(this);
	}
}
