package com.gmail.dmytro.ui.view.admin.location;

import com.gmail.dmytro.backend.data.entity.Location;
import com.gmail.dmytro.backend.data.entity.Product;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.*;
import com.vaadin.ui.declarative.Design;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class LocationAdminViewDesign extends VerticalLayout {
    protected TextField search;
    protected Button add;
    protected CssLayout listParent;
    protected Grid<Location> list;
    protected VerticalLayout form;
    protected TextField name;
    protected TextField country;
    protected TextField region;
    protected TextField city;
    protected TextField postal;
    protected TextField address;
    protected Button update;
    protected Button cancel;
    protected Button delete;

    public LocationAdminViewDesign() {
        Design.read(this);
    }
}
